### ISSUE TITLE
Improve Photoshop/Illustrator scripts

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-editor#169]
See

http://esotericsoftware.com/forum/photoshop-groups-as-skins-improvement-8092

**Comment by geddski** [comment]
Awesome. While we're at it - the script doesn't handle duplicate layer names well either. Say I have a model that has 2 arms (pretty common) with a layer tree like this:

```
zombie
  |--left arm
      |--hand
  |--right arm
      |--hand
```
once imported into Spine I would be left with only a single hand since the layers have the same name. The workaround is to make sure every single layer has a unique name which is tedious and frustrating to work with. Spine could detect the duplicate name and just append a number on the end.

**Comment by geddski** [comment]
or it could prepend the parent layer's name

**Comment by Shiu** [comment]
Created new issue for this

**Comment by geddski** [comment]
Thanks @Shiu. Did you guys already handle this? http://esotericsoftware.com/forum/photoshop-groups-as-skins-improvement-8092

**Comment by Shiu** [comment]
Not yet, we're doing multiple improvements on the script. You can see the new issue here #202.
