### ISSUE TITLE
Duplicate constraints

### ISSUE THREAD

**Issue by NathanSweet** [EsotericSoftware/spine-editor#183]
Provide a way to duplicate bones and all their constraints.

http://esotericsoftware.com/forum/Ease-of-Use-UI-Proposals-Improved-Tree-Animation-7463

**Comment by erikari** [comment]
and + 1 here: http://esotericsoftware.com/forum/Whats-the-proper-way-to-handle-3-bones-leg-10014

**Comment by erikari** [comment]
another +1 here: esotericsoftware.com/forum/Transform-Constraints-disappearing-10057

**Comment by erikari** [comment]
another +1 here: http://esotericsoftware.com/forum/Transform-Constraints-disappearing-10057

**Comment by erikari** [comment]
and another +1 here: http://esotericsoftware.com/forum/Request-wishes-separatewindows-groupbindings-and-more-11244

**Comment by alexpretty** [comment]
Same as transfering from one skeleton to another. At the moment, when you move some bones form one skeleton to another, the constraints are not duplicated.

**Comment by erikari** [comment]
Another +1 http://esotericsoftware.com/forum/duplicate-constraint-14489

**Comment by utkiupe** [comment]
Another +1 on the same topic 
BTW, do you thing this feature can be on the next update? It feels really important to duplicate constrains, especially when using them in skins in need variations from on skin to another...

**Comment by Joel-Hjerten** [comment]
4 years and ticking, I think it would be great if this were finally implemented, Today I'll have to great 5 animated horses (all of them needs to be in the same skeleton as well) based on a base horse with constraints and animations. Duplicating the horse loses all the constraints and I have to redo everything for each horse over and over again. This is costing A LOT of production time.

**Comment by titohuangkooapps** [comment]
Need dat duplicate constraints :)

**Comment by JQSpin** [comment]
This is becoming very frustrating. I often have to move full or partial rigs between skeletons or duplicate parts within one (like a leg of a millipede, just imagine having to do it for each and every leg over and over manually) and the lack of constraints duplicating or carrying over along with the hierarchy of what I'm duplicating is becoming really irritating. It's a huge time sink having to redo constraints manually over and over again. Please, please create a solution for this sooner rather than later as it's severely affecting my everyday work. And this is a feature that has been whished for since 2017, that is 5 years!

**Comment by studentsimfer** [comment]
Greetings from 2023!
Soon AI will take over the world but they won't implement copying constraints.

**Comment by NathanSweet** [comment]
4.2.59-beta
