### ISSUE TITLE
[Find and Replace] Find and remove unused attachments

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#200]
http://esotericsoftware.com/forum/Dont-export-unused-graphics-8749?p=39704#p39704

In case of a large, messy legacy Spine project, finding and removing unused attachments may be useful.

This seems like a good feature to add to the "Find and Replace" window.

Related features:
- Find attachments unused by setup pose
- Find attachments unused by any animation
- Delete found attachments one by one
- Delete all found attachments.

**Comment by erikari** [comment]
From http://esotericsoftware.com/forum/Questions-and-requests-9786 a user suggested:
> find keyframes of a certain slot through multiple animations
related to the export checkbox exporting an attachment anyway if there's a keyframe present.

**Comment by emjaykidd** [comment]
Just wanted to echo how wonderfully useful this would be for certain situations. In my case, I have complex rigs manually converted from Toon Boom Harmony, with as many as a hundred attachments per slot of pre-drawn frames (all the unique hand poses, facial expressions, etc that all require specific frames to match the art style of the source project). When it comes time to export, my current only recourse is to slowly comb through and try to find which poses I didn't use in order to better optimize the atlases. Being able to automatically select and remove them would be much less human error prone and worlds faster! <3 Rather than making it a tree filter (if this is any easier), it could also be nice to simply have some sort of "Export Only Keyed Attachments" checkbox toggle on the export settings.

**Comment by jgod** [comment]
Very very useful.

**Comment by Monkeyzav** [comment]
Still praying for this one :)

**Comment by erikari** [comment]
Another +1: http://esotericsoftware.com/forum/Reducing-unused-attachments-13386

**Comment by jgod** [comment]
For V4 release? ;)

**Comment by erikari** [comment]
Another +1: http://esotericsoftware.com/forum/Unused-slots-images-feature-suggestion-17295

**Comment by NathanSweet** [comment]
4.1.25-beta
