### ISSUE TITLE
Add exceptions for "Slot is hidden" export warnings.

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#220]
![spine_2017-07-11_21-49-07](https://user-images.githubusercontent.com/1911082/28095100-29c125c2-66d3-11e7-94d9-849c2dc6abba.png)

YES
- [ ] Don't show "slot is hidden" export warnings for slots have non-renderable attachments active.
  - `PointAttachment`
  - `PathAttachment`
  - `BoundingBoxattachment`

MAYBE
`ClippingAttachment` should be treated as renderable. (right?)
- [ ] Don't show "slot is hidden" export warnings for slots that have no attachment active(??)

**Comment by Rennan24** [comment]
Yeah this would be pretty nice to add in, Because when our animators are exporting the spine files it's annoying to have to keep clicking ok. The nice thing about having the Slot be disabled instead of the Attachment is that when we go to check for them on start, we don't have to use GetAttachment on SkeletonData.Skin or SkeletonData.DefaultSkin we can just use GetAttachment on the Skeleton which also gives us the correct skin depending on which one is assigned.

**Comment by NathanSweet** [comment]
3.7.35-beta only shows "slot is hidden" export warning for regions, meshes, and clipping attachments. Also has a checkbox to not show warnings at all after export.
