### ISSUE TITLE
Crash parenting attachments from one skeleton to bones in another skeleton

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#238]
http://esotericsoftware.com/forum/Crash-every-time-picture-is-parented-to-bone-9132?p=41377

**Comment by NathanSweet** [comment]
This issue has no repro steps. Also the reporting user included the wrong log which does not show the crash. We should push the user to both provide steps for how they cause the problem, and to provide the right crash logs.

@erikari You mentioned on the forum that we would show an alert instead of crashing, but this is not possible. A crash happens because the program gets in an unexpected state. Because it never expected to be in that state, it doesn't know if it can recover from or ignore whatever has occurred. To show an alert, we would need to understand what happened to put the program in a bad state, at which point we could just fix the problem rather than showing an alert. To understand what happened, we need repro steps.

I toyed around with the user's project and found repro steps that are most likely the same problem:
1) Click an image on the `Images` node (not an attachment).
2) Drag or use `Set Parent` to put the image in a different skeleton.
Actual: Crash.
Expected: Either allow or disallow the parent change.

**Comment by erikari** [comment]
@NathanSweet got it. Bad me. Will make better reports in the future. Thanks for explaining (:

**Comment by NathanSweet** [comment]
No worries. :)

Fixed in 3.6.40!
