### ISSUE TITLE
When removing weights from a mesh, attachments gets rotated

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#241]
Reproduced. This topic explains it clearly: http://esotericsoftware.com/forum/Mesh-deformed-arms-9149

**Comment by NathanSweet** [comment]
How do I repro this?

**Comment by erikari** [comment]
1. open raptor project
2. select front leg mesh
3. deselect the "mesh" tickbox
4. click "remove keys"
bug happens (:

**Comment by NathanSweet** [comment]
That seems to be a different issue. When converting from a mesh to a region with only 4 vertices, it is not easy to keep the region in the same place as the mesh. If the mesh was deformed at all, it is impossible. Note the raptor front leg (and body, arms, most of the meshes) are deformed.

When doing edit mesh `Generate`, Spine resets the mesh deform to match the UVs. It would be impossible to match the reset vertices to the old vertices if the old vertices were deformed (as the raptor front leg is), since by definition the vertices which match the UVs are not deformed. In 3.6.40 I try harder to keep the new vertices matching the old.

**Comment by erikari** [comment]
This still happens on the raptor leg as per repro case.
If I create a new mesh and leave it as the automatically generated image, the bug is not present
If I create a mesh with points that strip some space from the UV, it moves the attachment a little when I remove it. 
I understand it can't be done, just checking.

**Comment by erikari** [comment]
Well, I think this is related though:
![other mesh bug](https://media.giphy.com/media/3ov9jEgEFEvsQTgxY4/giphy.gif)

If only the editor didn't randomly rotate the attachment but keep its original rotation s: like the rotation of when the attachment is imported in Spine.

**Comment by NathanSweet** [comment]
The rotation shown for a mesh attachment is only adjusted when all mesh vertices are rotated. It may not represent the actual rotation for how the mesh appears, either due to moving less than all vertices or by the mesh being deformed by weights.

In 3.6.45, I improved keeping the mesh position when removing deformation for: `Reset` in the tree properties in setup mode, `Reset`, `Generate`, and `New` in edit mesh mode, and when converting a mesh to a region.
