### ISSUE TITLE
Move or add the  " Duplicate, Rename and Delete" buttons in the Animations panel

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#293]
Duplicate, Rename and Delete buttons in the Animations panel next to the name of the animation

reference topic:
http://esotericsoftware.com/forum/Feature-request-Animation-panel-w-Duplicate-Rename-Delete-9486

**Comment by NathanSweet** [comment]
You say "next to the name of the animation" but the screenshot shows properties at the bottom of the Animation view, like the tree has. I'm not sure I like putting the properties in two places. Animation is simple, since it has almost nothing there, but even then it isn't great because the Animation view allows for selecting only one animation at a time. Also, selecting an animation in the animation view makes it the visible animation, which isn't the same thing as selecting it in the tree.

Any other ideas?

You can already double click in the Animation view to rename. Right click selects the animation in the tree, as does single clicking the selected animation. `New Animation` is right of the Animations tab.

**Comment by erikari** [comment]
You're right, I misunderstood the position the user wanted. s:
We need a duplicate shortcut, unless you created it and I did not notice!

**Comment by NathanSweet** [comment]
You mean hotkey? It would duplicate the selected thing in the viewport or tree, so it would still require selecting the animation in the tree first.

**Comment by erikari** [comment]
I meant hotkey, my bad! 
It would still be faster that having to continuously move the hand up and down if you are duplicating the same animation/skin/bone more than once in the tree

**Comment by NathanSweet** [comment]
Yep, a duplicate hotkey sounds OK, but that's a separate issue. For this issue, what do we want for the Animations view UX-wise?

**Comment by bendsen** [comment]
It makes sense, why you don't wanna clutter the UI.
The reason why I prefer using the Animation panel and would love to see the dublicate/rename/delete buttons placed in this panel, is because it's always static.
When you're animating, the Tree panel is constantly jumping/scrolling up and down, if you don't have a rather simple skeleton setup. And if you're changing animation a lot, this becomes quite a hazzle, because you always have to relocate Animations in the Tree panel.

Quite some time ago i posted a mockup on a new UI layout for the Spine Editor focused on panels, just like Adobe have their layout.
Images, Animations and perhaps even Draw Order could easily be located in seperate panels, making the UI tailored for ones specific workflow.
When adding images to a complex skeletons, i end up scrolling a ton, which feels quite silly.

But I know, it would be a huge change - just wanted to clarify my wish and share my 5 cents.
Thanks for listening, guys <3

**Comment by NathanSweet** [comment]
In 3.7.35-beta selecting in the Animation view doesn't causes the tree to scroll, but still shows the tree properties. This allows you to duplicate, etc animations without needing to find it in the tree, and without needing more buttons in the Animation view.
