### ISSUE TITLE
After importing an animation it is impossible to change attachment inside a slot

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#309]
**Description of the problem:**
The attachments inside the slot in an animation are impossible to change/hide.
The animation was imported from a different skeleton.
If a new animation is created and the keyframes pasted in it, it works again for the new animation, but not in the old one, that has to be deleted.

**Repro steps:**
(The first steps are supposed because the repro file starts from n°3)
> 1. export json from a file
> 2. open second file (the repro project) and import 4 animations
3. in the repro project, go to Animate mode and select animation "idle_L"
4. select slot  "pic 39" from the tree view, you should be on frame 1
5. try to change the visible attachment from pic 39 to the other one inside the slot
6. scrub the timeline to frame 2 or press play
7. go back to frame 1: even though you changed the attachment visibility inside the slot, it's back to how it was on step 3.

Alternative solution to enable the user to modify the animation that does not solve the problem:

1. create a new empty animation
2. call it something random like "idle" (you'll rename it later)
3. select the animation "idle_L"
4. reset all filters in the dopesheet (as in the mail I showed you before, you need to be able to see all the keys)
5. press space to deselect everything
6. select the first row in the dopesheet and press ctrl+c
7. select the new animation and press ctrl+v
8. filter the dopesheet on "Attach" and delete the keys in "pic 39"'s row (I actually didn't need to do this step, it was correct after pasting, but in case, make sure the correct one is visible)
And it should all work now! you can delete the old animation and rename the new correctly.

**Repro project:**
Attached to mail of Jan 3

**Reference mail:**
16096be3b8cd948f

**Comment by HnatureWatcher** [comment]
hi~good morning! 
here is the project file & JSON which i used to import the animations "char_06.zip"
I imported animations from this files not from its JSON.hope it can help.
[char_06.zip](https://github.com/EsotericSoftware/spine-editor/files/1610555/char_06.zip)

**Comment by HnatureWatcher** [comment]
good morning!
here is the JSON exported from the file i used to imported animations.
i tried to upload the project file it self.but it's to many pngs make the zip over size.
i actually import animations from the file not the JSON exported. so i send the project file to erikari by email to make sure you have it when you need it .
thanks for your help.
[char_06_JSON.zip](https://github.com/EsotericSoftware/spine-editor/files/1610567/char_06_JSON.zip)

**Comment by HnatureWatcher** [comment]
hi good afternoon!
i just found this .hope it can help.
there is three pngs in "new discover.zip" two is in the file"char_10" the same animation has two "pic 32"
one is under  "bone61" the other is under "bone65". if you chose the "bone61"it has the attachment"pic 32" it's the real one. but if you chose the "bone65" there is nothing under this bone. it's weird.and i open the file"char_06" which i had imported animations to "char_10".
in this file.there is attachment "pic 32" under "bone65".maybe that's why there are two "pic 32" in the same animation. one is real one does not exists.

**Comment by HnatureWatcher** [comment]
hi good afternoon!
i just found this .hope it can help.
there is three pngs in "new discover.zip" two is in the file"char_10" the same animation has two "pic 32"
one is under "bone61" the other is under "bone65". if you chose the "bone61"it has the attachment"pic 32" it's the real one. but if you chose the "bone65" there is nothing under this bone. it's weird.and i open the file"char_06" which i had imported animations to "char_10".
in this file.there is attachment "pic 32" under "bone65".maybe that's why there are two "pic 32" in the same animation. one is real one does not exists.
[new discover.zip](https://github.com/EsotericSoftware/spine-editor/files/1610931/new.discover.zip)

**Comment by HnatureWatcher** [comment]
hi good afternoon!
i just found this .hope it can help.
there is three pngs in "new discover.zip" two is in the file"char_10" the same animation has two "pic 32"
one is under "bone61" the other is under "bone65". if you chose the "bone61"it has the attachment"pic 32" it's the real one. but if you chose the "bone65" there is nothing under this bone. it's weird.and i open the file"char_06" which i had imported animations to "char_10".
in this file.there is attachment "pic 32" under "bone65".maybe that's why there are two "pic 32" in the same animation. one is real one does not exists. and i check every attachment which can not hide or show. they  all had the same situation!
[new discover.zip](https://github.com/EsotericSoftware/spine-editor/files/1610949/new.discover.zip)

**Comment by HnatureWatcher** [comment]
hi...good evening!
finally! i know how to deal with this problem now. it's only about the attachment with the same name. when it's happened just need to delete the key frame of the fake one which created by imported.it's just the key frame information. but it's effect the real attachment's key frame information.
and after all this. next time i use the "rename layers" plug-in components. i'll change the code"layers[i].name = "pic  " + [i];    to    layers[i].name = "char_0X " + [i];  no more same names.
i made a little test with this sample charactor. it will be all ok.
thanks for you help. bye~

! ![image](https://user-images.githubusercontent.com/35208287/34670753-a7c58766-f4b2-11e7-91d6-d04ae20d1f61.png)
!

**Comment by NathanSweet** [comment]
This is very confusing. Apparently @HnatureWatcher imported bad data. Just looking at the resulting bad project doesn't help, we would need the bad data that created the project. Exporting the project doesn't result in the original bad data for reasons. If @HnatureWatcher can provide the bad JSON data, we can reopen this issue and have the importer show an error. Without the bad data, there's nothing we can do.
