### ISSUE TITLE
Duplicate skin functionality doesn't copy mesh animations

### ISSUE THREAD

**Issue by lagoPS** [EsotericSoftware/spine-editor#321]
When duplicating a skin of an animated skeleton that contains animations with mesh animations, the mesh animations are not duplicated into the animations of the new skin.

The expected behaviour should be that all mesh animation keyframes get copied to the animations of the new skin, as mesh animations are managed per-skin.

**Comment by erikari** [comment]
Hi lagoPS, thanks for creating an issue!
I'll add a repro case:

1. open the goblin project
2. in animate mode, the goblin's left and right foot have deform keys, look how they deform
3. in setup mode, select the goblin skin then duplicate it
4. in animate mode, the new skin lost all the deformations

**Comment by lagoPS** [comment]
Thanks erikari! ^^

One more sidenote:
The problem should happen even if you only have a single key for the mesh slot in the first frame of any animation, that just displaces that mesh from its setup position.

But in general, I guess that it happens for any mesh/slot keys, which appear to be not duplicated to the new skin animations.

**Comment by pharan** [comment]
This is a missing feature rather than a bug. Duplicating a skin duplicates the meshes, rather than creating a new linked mesh linked to the original.
I've noted this missing functionality before. Internally, we have an tracker for it. I've linked this issue in that thread.

"Duplicate skin workflow Improvements"
(1) Offer to make linked meshes instead of deep copies of the original meshes.
(2) Offer to open the find and replace window immediately after duplicating, and have handy defaults when it opens.

---------
For now unfortunately, you have to delete those meshes and create new linked meshes linked to the originals manually. 

You can learn more about linked meshes here: http://esotericsoftware.com/spine-meshes#Linked-meshes

**Comment by lagoPS** [comment]
@pharan I guess my question is: shouldn't duplicating the meshes also duplicate all the respective mesh/slot keys in each animation?

**Comment by lagoPS** [comment]
One additional information.

The specified problem only happens when the skin being duplicated already has skin placeholders that contain the animated mesh.
The problem does NOT happen if there are no skin placeholders parenting the animated mesh.

**Comment by pharan** [comment]
Yeah. As a user when you duplicate a skin, you may a) want to link your duplicate meshes to the meshes in the original skin (which also causes it to share the original animation. any edits to the original mesh or animation is applied to the linked meshes), or b) want an independent copy of the mesh and the animations so you can edit them without affecting the original.

Yeah, I've added these issues to the thing.

Thanks for the additional details. That'll help iron out the feature.

**Comment by yvescapion** [comment]
Hi guys! Would it be possible to know if this feature will be implemented because it looks like a big bug relative to the skin feature of the tool? Actually, we're really stuck by it on our side.

So do you have some news about it?

**Comment by NathanSweet** [comment]
As Pharan mentioned above, this is a missing feature rather than a bug. Our internal issue for improving the workflow for skins is slated for 3.7, so this issue should also have the 3.7 milestone.

Note that deform keys take up a lot of space in the animation data. Duplicating all the deform keys for a mesh could be a lot of data. It is also difficult to maintain: if the deform keys need to change, there are many copies of them. Still, I do understand the use case and we will implement the feature.

Note that an alternative can be to use mesh weights. Instead of animating the mesh vertices, you animate the bones the mesh is weighted to. This way meshes in different skins are animated by the same bones, so any changes made to the bone animations will affect all the meshes.

**Comment by NathanSweet** [comment]
It's in 3.7.31-beta!
