### ISSUE TITLE
Auto name paths on creation

### ISSUE THREAD

**Issue by Shiu** [EsotericSoftware/spine-editor#329]
When creating a new path, set the name of the path to the same as the bone it was created on. 
It's possible this would need a checkbox to toggle the auto naming on/off

http://esotericsoftware.com/forum/Please-add-default-name-for-new-Path-10003

**Comment by NathanSweet** [comment]
Where would a checkbox to disable this go? The user wants creating a new path to not prompt a name dialog at all.

I disagree with naming a path under bone `Tail` to `Tail's path 1`. It would make more sense to name it `tail1` rather than embedding the type of attachment in the attachment name. However, it may be the case that I'm creating a path for another reason. Eg, maybe a bone has 3 paths for different things, unrelated to the naming of the parent bone (which could be `root`).

An enhancement that is likely more acceptable would be to avoid prompting for a name at all. Eg, `path`, `path2`, `path3`, etc like we do when creating new bones.

If we chose to make a change for how path names are prompted, we should probably apply the same changes to other attachment types where we prompt for a name.

**Comment by fantasyz** [comment]
In my opinion, using path1, path2, path3 would just force users to type a name for the path unless the name really doesn't matter and there is no much path in the project to be confuse with. 
One benefit of using BoneName's PathX is that even if using this default name, user can still  know roughly that that path is about. Like 
Medusa Hair's Path1, 
Medusa Hair's Path2, 
...
Medusa Hair's Path10

Because the name is under a bone, the count would generally start from 1 which also make the things more clear. I can easily tell how many paths are there under the tail bone by just looking at the largest number. And people generally like to deal with small numbers.

When hierarchy search box is implemented. I can easily filter those paths out by the bone name without renaming each path from pathX naming.

Maybe the dialog could show something like is to suit different kinds of preference: 
---------------------------------------------------------------
Enter a name for the Path: 

( X ) [ path1             ]  << check box and input box
(    )  [Tail's path1  ]

[    ] don't show again.                                 [OK] [Cancel]
---------------------------------------------------------------
The prompt then could remember the last choice whether it is simple path1 or name by parent.

**Comment by fantasyz** [comment]
hmm....
I don't know why some text are so large in the previous message...
(I didn't use any magic BBCode. )

**Comment by fantasyz** [comment]
ok... I think it is the dash line I typed causing the text to be enlarged. Sorry about that.

**Comment by NathanSweet** [comment]
We now choose the skin placeholder, slot, or bone name as a default, with a number appended. We still prompt for the name, but provide the default value, so you can just hit enter. Also note in 3.7 many objects can be selected and renamed at once, which will append numbers to make the names unique, as needed.
