### ISSUE TITLE
Double clicking on the project file makes Spine remember path even on new projects

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#376]
**Description of the problem:**
If Spine is launched by double-clicking on the project file, it appears as it stores in memory that path even when a new project is created, causing meshes to be loaded incorrectly if, for example, the user wants to load the same project at half the dimension.

This problem is absent if Spine is launched through the App icon instead.

**Reference thread:**
http://esotericsoftware.com/forum/Import-data-issue-with-folder-path-10658?p=48174#p48174

**Repro project:**
[Birthday Moo](https://www.dropbox.com/sh/agk7vnc5nbkctmg/AADtcG1t9Gm5t1yeymhhRpTHa?dl=1)

**Repro steps:**
1. double click on the Spine project file (in this case `birthday-moo.spine`) to launch Spine
2. export a json in the folder called `export` (you can skip this step, I already did it)
3. Drag the exported json in the Spine window to load it, select new project, set the skeleton dimension to `0.5` and confirm
> Images will have this super funny aspect
![moo kangaroo](https://image.prntscr.com/image/D8rcbrPwTWWGdAFpNIh_eg.png)

**Alternate repro steps that don't present the problem:**
1. double click on the Spine program icon to launch Spine
2. repeat steps 2-3 from the previous repro steps
> Images will show missing
3. select the correct folder, `images-half` to see Moo with correct proportions
> Images will be correct
![moo ok](https://image.prntscr.com/image/PZqKopw6SZmWdRVgvj5lNg.png)

**Comment by NathanSweet** [comment]
When Spine is run normally, the application working directory is the Spine install folder. When the data is imported, the relative images path `./images` cannot be found.

When Spine is run by clicking a project file, Windows sets the application working directory to the directory containing the project file. When the data is imported, the relative images path `./images` is found and the meshes adjusted (per the [mesh adjustment rules](http://esotericsoftware.com/spine-meshes#Image-resize)) because the meshes are half size but the images are full size. After changing the images to the half size images, the adjusted meshes look wrong.

We should probably never look in the application working directory. To do this we need to be careful to never treat a relative path as an absolute path. So far we try a path and if not found, we assume it's relative and try it relative to the project file folder.

**Comment by NathanSweet** [comment]
3.7.31-beta
