### ISSUE TITLE
CL doesn't respect "false" in flatten paths on beta

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#399]
**Expected:**
Folder structure retained so that duplicate images get exported anyway
**Actual:**
Error for having the same name for an image twice
**Steps:**
1. download repro mail files
2. Launch Spine from CL
3. if on windows, change directory to Spine's one, then launch a command similar to this:
`Spine -i ".\tuner_unity\tuner_unity.spine" -o ".\export" -m -e ".\tuner_unity_0af9685f-7d19-4be2-a985-4e63c3978ccf.json"`
> you will get this error: 
![error](https://image.prntscr.com/image/QmyUBMZdR7mwkhW5U0ekGQ.png) 
even if you change the repro json to flatten paths/combine subdirectories false

**Repro mail:**
FMfcgxvzLXCwzDflzSvwQDMNLlkFJjvh

**Comment by NathanSweet** [comment]
The project has two skeletons with the same images path, then the export uses:
![](http://n4te.com/x/5334-d5Tt.png)
This packs the same images twice and fails on the second because a region with that name already exists in the atlas.

We should detect this and avoid packing the images twice.

**Comment by NathanSweet** [comment]
Binary export with packing is the problem for this project, and there this is used (same as in the export settings JSON file):
![](http://n4te.com/x/5336-ETv3.png)
Note the error can be seen either at the CLI or in the UI.

The problem is that the project contains two skeletons with the same name, which is not allowed. When exporting an atlas per skeleton, when the second atlas is exported it finds the atlas files already exist, because the atlas is named after the skeleton. It tries to add to the existing atlas, which already contains the regions.

How did two skeletons get the same name? That is the problem we need to fix. If we get that information, we can reopen.

**Comment by NathanSweet** [comment]
3.7.52-beta: Fixed CLI data import allowing skeletons to have the same names.
