### ISSUE TITLE
Preview view - Additive blending is not applied if the animation track is active, before enabling additive blending.

### ISSUE THREAD

**Issue by Shiu** [EsotericSoftware/spine-editor#401]
![](https://i.imgur.com/onSNz9E.png)

Attached project can be used for reproduction
https://esotericsoftware.slack.com/files/U16HRKN4D/FE6CZK1UZ/additive-blending-bug.zip

**Comment by NathanSweet** [comment]
So, `additive` doesn't change any existing track entries (there may be many entries for a single track: the current entry and any number of entries being mixed out) -- it is not applied until a new track entry is set. This is also true for `mix time` and `hold previous`, though only the `mix time` tooltip makes it clear:
![](http://n4te.com/x/5424-x7nb.png)
The `alpha` setting *does* affect the current entry, because doing that is useful and often how it is done at runtime.

Note you might want to set `mix time` and `hold previous` differently for different animations on the same track, so if they affected the current entries, it would make that impossible. You probably never want to use additive and non-additive entries on the same track, so you'd press `additive` before setting entries and never turn it off.

Any ideas for how to make this more clear? If so we can reopen!

**Comment by NathanSweet** [comment]
Ha, I'll fix the typo in the tooltip!
