### ISSUE TITLE
Complex constraints suddenly changing position and angle

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#456]
Unsure if bug or normal constraints behavior, but the behavior is confirmed.

Repro steps:
1. Open project `blonde.spine` attached to the mail
2. in animate mode, select the animation `idle2-selfi`
3. ` l_hand` bone rotates and the whole arm changes position greatly on frames 28 and 29.

Repro mail:
FMfcgxwCgCTptXpqhRTlRlmqQSXptFMT

Considerations:
This setup has multiple constraints. Changing constraints order did not solve the problem, adjusting the path during the animation shows the same behavior. I could not isolate a constraint outside of the path constraint as the cause of the behavior, my guess is the parenting and correlation of targets caused the shortest possible solution to differ greatly in the space of few pixels. 

It is unclear why this would cause the target to rotate. The rotation of the target should not influence the constraints position so the two could also be different issues.

**Comment by NathanSweet** [comment]
The snapping happens due to the rotate mix on the l-hand path constraint. This is a gotcha to look out for whenever rotate mix is used. It is easiest to understand with a transform constraint using 50% rotate mix:
http://n4te.com/x/6447-rotation-mix-example.spine
As the target bone rotates, the constrained bone rotation wants to be 50% of the way between the constrained bone's rotation and the target bone's rotation. There are two possibilities: 50% the short way around or 50% the long way around. For consistency, Spine always chooses the short way. When the target bone rotates far enough, what was the short way around becomes the long way, and so the constrained bone jumps to the other side.

This exact same thing can happen with path constraint rotate mix.
