### ISSUE TITLE
[trim] and [notrim] tags for the PhotoshopToSpine script

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#558]
A suggestion to add two new tags that would override the whitespace trimming setting:

`[trim]` to trim a layer
`[notrim]` to leave the layer size as the document maximum bounds

**Forum thread:**
http://esotericsoftware.com/forum/Suggestion-Photoshop2Spine-script-Trim-NoTrim-tags-13985

**Comment by NathanSweet** [comment]
The PS script has supported this for some time, using `[trim:false]`. Also 4.2 supports [processing PSDs directly](http://esotericsoftware.com/blog/Import-PSDs-directly-no-Photoshop-scripts-needed) and there you can use `[trim:mask]` to trim using the clipping mask bounds instead of the whitespace bounds.
