### ISSUE TITLE
[PhotoshopToSpine] v7.09 can't export if [folder] name and [skin] name are not matched.

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#608]
v7.09 can't export if the name specified using [folder] tag and the name specified using [skin] tag are not matched.
![PhotoshopToSpine7-09_AnIssueOfFolderName](https://user-images.githubusercontent.com/85478846/138020186-3c6df552-d2b9-4c9c-9daf-12bcc61eb5c0.png)

This issue was reported in this post by Kuro Kei :  http://esotericsoftware.com/forum/viewtopic.php?f=3&t=16372

**Comment by NathanSweet** [comment]
What is the goal for putting skins under a folder group? To have the skins appear in folders in Spine? That can be achieved using forward slashes, eg a folder named `[skin] A/B` will show up in Spine as a folder named `A` with a skin named `B`.

In 7.11 we've improved the script so skin names use any parent folder groups. The error in this issue should never be possible now, though I left it in as a sanity check.

Note placeholder names are the folder paths relative to the skin group + layer name. To be clear, this PSD:
![](http://n4te.com/x/3513-7Bjb.png)
Results in this JSON:
```
"slots": [
	{ "name": "head", "bone": "root", "attachment": "red" }
],
"skins": {
	"A/A": {
		"head": {
			"red": { "name": "A/A/red", "x": 414, "y": -551, "width": 172, "height": 340 }
		}
	},
	"A/B": {
		"head": {
			"green": { "name": "A/B/green", "x": 1230.5, "y": -709.5, "width": 179, "height": 355 }
		}
	}
},
```
The placeholder name is `head` because that is the path relative to the skin group. It is not `A/head` because the folder group above the skin group is not used in placeholder names.
