### ISSUE TITLE
Latest X.X will be converted as "Latest stable" and make unintentional version change

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#622]
For example, if you choose Latest 3.8 to switch the editor version to 3.8.99, the setting will be converted Latest in 3.8, so the latest stable version (currently 4.0.56) will be launched on the next run unintentionally.

This problem was reported on this post:
http://ja.esotericsoftware.com/forum/Latest-4-0-to-3-8-99-Spine-keeps-latest-4-setting-16888?p=74030#p74030

**Comment by NathanSweet** [comment]
To repro this, when running 3.8.99 the settings dialog must be opened and saved. If the 3.8.99 settings dialog is not saved, this bug does not occur. This is why we haven't noticed the problem until now.

3.8.99 doesn't recognize the `Latest 3.8` version (represented as `3.8.xx`), so the 3.8.99 settings dialog shows `Latest`. When saved, it saves the version as `Latest` (deleting `version.txt`), losing the `Latest 3.8` setting.

This is unfortunate. We can't stop the old code in < 4.0 versions from doing this. We can remember that we last launched a < 4.0 version and if we see `version.txt` is gone, use the last launched version instead. We'll do this in the next launcher update, 4.1.03.

If the user removed `version.txt` because they actually want the latest, this means they will be surprised by this behavior. We'll still do it since it is uncommon for a user to remove `version.txt`.
