### ISSUE TITLE
Exporting with many Spine instances will cause the editor version to be changed to the latest stable version

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#668]
**Description:**
Exporting with multiple Spine instances using CLI may unintentionally change the Spine editor version to the latest stable version. This is more likely to occur the more instances that are launched, but not when run alone.

Below are the logs provided by a user:
```
WARNING: Unable to write to shared folder: C:\ProgramData\Spine
[filenotfound] C:\ProgramData\Spine\test (プロセスはファイルにアクセスできません。別のプロセスが使用中です。)
   at java.io.FileOutputStream.open0(Native Method)
   at java.io.FileOutputStream.open(Unknown Source)
   at java.io.FileOutputStream.<init>(Unknown Source)
   at java.io.FileOutputStream.<init>(Unknown Source)
   at s.Otf._(_:398)
   at s.DIo._(_:174)
   at java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source)
   at Launcher.start(_:217)
```
Some time after the above warning, the following error occurs:
```
ERROR: An error occurred starting 4.1.06: C:\Users\user\Spine\updates\4.1.06
[error] Error validating update file.
   at s.Mpy._(_:1010)
   at s.Mpy._(_:486)
   at s.Mpy._(_:135)
   at s.Mpy._(_:484)
   at s.jOK.V(_:134)
   at s.jOK._(_:117)
   at s.jOK._(_:113)
   at s.mmT._(_:261)
   at s.afy._(_:57)
   at s.uza.C(_:348)
   at s.uza.V(_:354)
   at s.uza.V(_:219)
   at s.Pvd.V(_:270)
   at s.Mpy._(_:278)
   at s.Mpy._(_:162)
   at s.jOK.V(_:55)
   at s.jOK.Z(_:29)
   at java.lang.Thread.run(Unknown Source)
Cause: [error] [0x05]
   at s.Mpy._(_:1000) ...
```

**Expected behavior:**
Starting many instances does not change the editor version.

**Workaround:**
Using `-u` or `—update` to specify the version to launch avoids this issue.

**Version in which this issue was found:**
Spine launcher v4.1.07 / v4.1.08

This issue is reported in this forum thread:
http://esotericsoftware.com/forum/Spine-17362

**Comment by nikes** [comment]
+1
Where start more 12 instances at the same time

**Comment by NathanSweet** [comment]
The `Unable to write to shared folder` error is harmless, but we will fix it in launcher 4.1.09.

It isn't clear why the `Error validating update file` would occur.

I run the UI and set the version to 4.0.64, then ran 30 Spine instances via the CLI to do a GIF export. All 30 runs succeeded. I tried it multiple times. I never got a failure and the version stayed 4.0.64. I ran the exports with this Windows batch file:
```
for /L %%i in (1,1,30) do (
start /B spine -i template.json -o test%%i.gif -m -e spine.gif.json
)
```
I'm not sure what else we can do. If someone can provide a batch file and the project and export settings that causes the error to occur, only then we can fix it.

**Comment by NathanSweet** [comment]
Any ideas how I can reproduce the problem? Can you guys make a Windows batch file that causes the problem to occur?

**Comment by NathanSweet** [comment]
We will reopen this issue if someone can assist us in reproducing the problem.

**Comment by sbrednikhin** [comment]
@nikes - you can try to reproduce using script from here:
https://github.com/EsotericSoftware/spine-editor/issues/668

**Comment by NathanSweet** [comment]
Sorry for the delay! We've fixed this in launcher version 4.2.00. This Python script can now run successfully:
```
import subprocess
from threading import Thread, Lock
import os.path

n_runs = 300
n_threads = 32

c_threads = 0
i_proj = 0
n_proj = 8
mutex = Lock()

def launch_export(index):
    global n_runs
    def launch_with_callback(index):
        global c_threads

        mutex.acquire()
        c_threads += 1
        mutex.release()

        p = subprocess.Popen(['C:/Dev/spine/other/installs/Spine/Spine.com', '-i', os.path.join('source', 'proj{}.spine'.format(index)), '-o', os.path.join('dest', '{}'.format(index)), '-e', os.path.join('source', 'to_binary.json')])
        p.wait()
        
        mutex.acquire()
        c_threads -= 1
        mutex.release()
        return
    mutex.acquire()
    n_runs -= 1
    mutex.release()
    
    thread = Thread(target=launch_with_callback, args=[index])
    thread.start()
    return thread

while (True):
    mutex.acquire()
    if (n_runs <= 0):
        break
    mutex.release()

    if (c_threads < n_threads):
        mutex.acquire()
        print(n_runs, i_proj)
        mutex.release()

        launch_export(i_proj)
        i_proj += 1
        if (i_proj == n_proj): i_proj = 0
```

**Comment by NathanSweet** [comment]
Before running multiple instances of Spine, you should ensure that the update file for the version of Spine you want to run has been downloaded. For example, you can do that with this command:
```
spine -u 4.1.23 --version
```
Afterward you can run as many concurrent instances of Spine that use that version, or any other downloaded version you find here:
```
Windows: <user home folder>\Spine\updates
Mac: <user home folder>/Library/Application Support/Spine/updates
Linux: <user home folder>/.spine/updates
```

## Why, though?

When multiple Spine instances try to download the same update version, they will all want to place it in the same location in the user directory. Spine validates that the update file it will run is the actual file downloaded by that instance. This will not be the case if another instance has replaced the file. In that case you will get an `Error validating update file.` message.

It is also possible that another process replaces or deletes the update file. This can cause all sorts of problems but usually Spine will crash with an error that says `[eof]` for "unexpected end of file". Pulling the rug like this can also result in other errors.

Spine uses file system locking to signal that the update file is in use. When this is the case Spine will give an error like `The update file could not be written. Is it in use?`.

In all of these cases, the Spine invocation will fail. File system locking is not robust enough to prevent multiple processes from stomping the update file. File locks work differently on Windows/Mac/Linux and are generally only advisory. In some cases mandatory locks are possible, but even then they cannot protect against all operations. For example, writing to the file can be prevented in some cases, but replacing it cannot.

In the future we will use an inter-process communication mechanism so that only the first Spine instance downloads and the others wait it to be finished. Until we have that, it shouldn't be too much of a burden to ensure the update file for the version you want to use has been downloaded.

**Comment by NathanSweet** [comment]
In 4.2.01 we've added inter-process communication, so only the first Spine instance will download the update and the others will wait.

**Comment by NathanSweet** [comment]
4.2.01 is available now.
