### ISSUE TITLE
Tree doesn't refresh after UNDOing a drawing order change in ANIMATE mode

### ISSUE THREAD

**Issue by bencresty** [EsotericSoftware/spine-editor#672]
While animating days in a row it happened to me a few times now that I needed to change the drawing order and changed it, but forgot to go to the setup mode first (as it should be changed in the general setup pose).

When this happens the first thing I do is ctrl-Z to undo. Just to find out that this action is not undoable and so something else was undo-ed. Which is obviously not what I was after and at these moments I don't even know what has changed as that might be something completely out of view (it is most of the time actually). And than I'm lucky I checked if the change was undone. Because in a hurry it's easy to forget to check this and then later you just found out there's something changed in the animation without knowing the reason (not knowing it was this unwanted undo). So then we have 2 mistakes in our scene: one drawing order not set the right way and one undo that wasn't suppose to happen. As you see this is confusing and prone to errors.

Please add an undo level to the drawing order change! At least when done in the animation mode (to restore the keyframe and drawing order)!

Spine version: 4.1.06

**Comment by NathanSweet** [comment]
I'm unable to reproduce the problem: I opened the spineboy example, in animate mode I changed draw order by dragging in the tree, then pressed ctrl+Z and the draw order changes were reversed.

Please note for bug reports we need:
1) Steps taken to reproduce the problem. This lets use see the problems firsthand so we can both fix it and verify the fix is correct.
2) What you saw happen.
3) What you expected to happen.

**Comment by bencresty** [comment]
@NathanSweet 

1. Steps taken to reproduce the problem:  - go to animate mode, - change drawing order, - use ctrl-z
2. What you saw happen: nothing
3. What you expected to happen: undo the drawing order change (so the blue icon on the changed element in the drawing order to dissapear)

BTW I saw the undo on the drawing order in the SETUP mode IS working, so it seems to only be the ANIMATE mode

**Comment by bencresty** [comment]
@NathanSweet  starting a new file from scratch I see the following happening when UNDO'ing:

- The keyframe is indeed undo'ing
- The tree seems to be changed, but it doesn't show the changes as the tree isn't refreshed. It only refreshes when switching to SETUP mode and back to ANIMATE again

So it looks like undo does work, but we can't see it

**Comment by bencresty** [comment]
https://user-images.githubusercontent.com/69322733/180610767-f7706f49-4aba-44fb-93ac-555470ac51c2.mp4

**Comment by NathanSweet** [comment]
What seems obvious may only occur with your project file (using an example project we both have helps), or you have some settings I don't (auto key, etc), or there is some other difference that matters (eg what views are open). What is important can sometimes be very obscure, such as a problem that only occurs after taking other actions (it can help to start Spine anew).

It's too much work to compensate for *every* variable and usually that's not necessary, but simple structured "1) steps to reproduce, 2) actual behavior, 3) expected behavior" makes a good starting point for investigation. Otherwise I can easily go clicking around but not see or understand the issue.

At any rate, I got it now, thanks! The key created by auto key is getting its own undo state and the draw order change gets another undo state. They should be combined into one undo state.

**Comment by bencresty** [comment]
@NathanSweet good to see you found it :)

**Comment by NathanSweet** [comment]
4.1.07
