### ISSUE TITLE
Please add toggle to use TL in and out points to preview only that range of the current animation in preview

### ISSUE THREAD

**Issue by bencresty** [EsotericSoftware/spine-editor#675]
I think the reason why needs a little explanation, so if you don't mind, here's why:

I am working an animations which have a path animation which moves the object along a path. Next to this there are animated parts of the object itself.

It was necesary to create the path animation first (so before animating the object itself which moves along the path). So, to be able to keep the object on the screen to animate that, I needed to turn off the effect of the path constraint by setting the mix values to 0 and add temporary keys of that on the first frame. When the object animation is finished I than only need to remove those mix-keyframes and the object moves along the path AND is moving itself.

The loop of the object animation has less frames than the path animation. So I use in and out points in the timeline to work on the looping animation of the object parts (and when one run is nice and done, I copy the keyframes to make the length the same as the path animation length.

In the meantime I have a preview panel open to preview the object animation loop, but it seems to ignore the in and out points of the timeline. This isn't ideal, because now I need to wait everytime before the preview finishes the keyframes until the path animation (which effect was turned off, but is still on the timeline) finishes. Just to see 1 run of the object animation, and need to wait again for the path animation to finish.

I'd like to use the preview window, next to playing and stopping in the timeline, because it's way easier to see how the final result would look like and we can set it to a different scale.

**Would it be possible for you to add a toggle to the preview window to enable respecting the in and out points of the currently selected animation? That would make the preview, which I really like btw, a lot more useful in these kind of situations.**

Thanks for considering!

**Comment by NathanSweet** [comment]
In 4.1.07 the Preview respects loop start and end for all animations when in animate mode and the Preview setting `Play current animation` is active.

![](http://n4te.com/x/5172-fxeE.png)

We're dual purposing that checkbox somewhat, but checking it is saying you want Preview playback to be related to the currently active animation, so 1) changing the active animation changes the Preview animation, and 2) loop start/end applies.

**Comment by bencresty** [comment]
Cool! Thanks!

**Comment by NathanSweet** [comment]
I'll add some notes from more discussion with the team:

Applying loop start/end to Preview works, but the Preview is intended to show how animations look at runtime. It may be a bit surprising to have loop start/end affect Preview because, while you can get the same effect at runtime via code (by setting TrackEntry animationStart/animationEnd), loop start/end is not exported from the editor. Also when changing animations in Preview they are still affected by the mix duration. It's pretty odd to mix from one animation to another when both are only playing between loop start/end.

The Outline view may be a better solution, the downside for your use case being that it can't apply multiple animations at once. We'll keep the new Preview behavior when `Play current animation` is checked. In 4.2 we'll likely give it its own checkbox. Later we'll replace it with better controls for configuring the animations in Preview (#371), which will better match how animations are configured at runtime.
