### ISSUE TITLE
[issue] When visually translating only x or y with locked axis on seperated translation, Spine adds keyframes to other, non-changed, axis

### ISSUE THREAD

**Issue by bencresty** [EsotericSoftware/spine-editor#690]
To my surprise Spine is adding keyframes to the non-changed other axis of a seperated translation. 

When only moving in a locked axis using the red and green arrows I would expect only keyframes to be added to that axis when seperated is selected. It looks like this issue only appears on translation and when dragging the arrow in the direction of the bone/slot itself. 

Please see video below (Spine 4.1.08). As you can see Spine is adding a keyframe to the x-axis, eventhough the translation is seperated and nothing has changed to that x-axis, because only the y-value is change by dragging the red arrow.
In this example the issue doesn't seem to be there when moving the red-arrow UP (moving away from the bone/slot), so I have the impression Spine internally 'thinks' it's moving both axis, just because the cursor, while dragging and while mouse button is till down, left the red arrow on screen.

I believe, but am not sure, this is only happening on translation.

https://user-images.githubusercontent.com/69322733/184865139-55ac33e7-751b-4e1f-ba54-a257220daeeb.mp4

**Comment by misaki-eymard** [comment]
Thank you for your report! I was able to reproduce the problem on my end, so I would like to add some additional information about the steps to reproduce the problem.

------

This problem does not occur in the translating X or scaling X/Y and shearing X/Y. Only moving the Y-axis arrow of the translation causes the problem.
When I reproduced this problem, there was a "threshold" for the amount of movement that would cause the problem. For some reasons, it seems that any amount of movement on the Y-axis greater than ±230 causes the key to be recorded on the X-axis.
https://user-images.githubusercontent.com/85478846/185281032-29533ce2-3832-49df-bf15-b0b135690f69.mp4

However, the video benresty gave us showed that the key was recorded on the X-axis immediately after the Y-axis arrow was moved, so there may be some different condition. But as far as I could tell, for example, if the bone was originally at Y:200, the key was recorded on the X-axis once it exceeded Y:430.

**Comment by NathanSweet** [comment]
This problem is due to floating point inaccuracies. Bone positions are stored using `Parent` axes. In both videos `Local` axes are selected. The math necessary to convert between coordinate systems can introduce some amount inaccuracy depending on the magnitude of the values. This will also occur with `World` axes, but should never occur with `Parent` axes.

For example, when reproducing the issue as shown in Misaki's video, the X translation that is keyed at +/-230 Y translation is `0.00001010574`. In other cases I've seen it as high as `0.0002950518`.

Not that because the bone translation is stored in the `Parent` axes, the follow is true:
* When using `Local` axes, if the local axes do not match the parent axes, then you will always get both X and Y keys.
* When using `World` axes, if the world axes do not match the parent axes, then you will always get both X and Y keys.

While the math issue may be surprising, it's very common to rotate, scale, or skew a bone so the parent axes do not match the local or world axes. In that case, you must use the `Parent` axes to key only translate X or Y. This lessens the importance of fixing this issue somewhat.

Fixing the issue will require rewriting some portions of the translation code to use more accurate data types and matrix operations. We would not want to increase the threshold for comparing translate key values.

**Comment by NathanSweet** [comment]
We have increased the accuracy of bone transform math in 4.2.00, so this issue is effectively fixed. Technically it's still possible to see such anomalies since there are still floating point conversions happening, but I couldn't find any situation where it occurs.
