### ISSUE TITLE
Pressing CTRL+S to save a project then ENTER doesn't actually save the project if the older version warning shows.

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#697]
As per title, this also shows on the Spineboy example project if opened in v4.1.08
Press CTRL+S
Then press ENTER
the toast disappears but the file isn't saved.

Expected: either a repeated warning that the project is not going to be carelessly saved, or the file actually being saved.

**Comment by NathanSweet** [comment]
On dialogs that perform a dangerous action, `enter` chooses the safer action because users tend to go on autopilot and hit enter when they see a dialog just to make it go away because reading takes effort. For example, on the dialog you mention or on the "You project has unsaved changes" dialog, `enter` gives you `Cancel` and not `Save Changes` (on both dialogs `S` will save).

I agree this could lead to thinking a save happened when it did not, which is quite bad. It would be better to have `enter` (and `space`) do nothing. `escape` will give "cancel", if that is desired.

**Comment by NathanSweet** [comment]
4.1.10
