### ISSUE TITLE
Add warnings for skin placeholders

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#698]
If a bone is in a skin and has children that are in more skins than the given bone, no warning is displayed on the children attachments.
This could maybe be irrelevant if we had the warnings view, but so far one is left wondering why a mesh cannot be moved at all.

Found this when I tried to move Misaki's "hair-front" mesh vertices in the chibi-stickers project
https://www.erikari.it/uploads/1263-chibi-stickers-repro.zip

**Comment by NathanSweet** [comment]
It's kind of borderline, but technically it's not invalid rigging. The `hair-front` mesh's parent bone is not active because it's skin is not active, but the mesh is not weighted to its parent bone at all -- that's why it renders correctly.

The reason you can't move the mesh vertices is the editor uses the parent bone coordinate system during translation. It is also used for other things, like `Parent` axes. When the parent bone is inactive, the coordinate system is zeros (a mathematic black hole). The applies to meshes, bounding boxes, clipping, and paths (everything with weights).

We'll workaround this in 4.1.10 by using the first bone in the weights list when the parent bone is inactive. There may be situations where the parent bone is still used, so keep an eye out for other things working incorrectly when using this rigging.

Even with 4.1.10, `Hide skin bones and constraints` needs to be checked, else the parent bone (and therefore the mesh) is not shown at all.
