### ISSUE TITLE
More mesh editing features

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-editor#70]
See below mock-up.

![http://sht.tl/1U1oTa](http://sht.tl/1U1oTa)

**Comment by NathanSweet** [comment]
1) You can currently multi select vertices by holding control and dragging a box or clicking individual vertices. A related tip is to use selection groups with vertex selections:
http://esotericsoftware.com/spine-tools#Selection-groups
Eg, select vertices, press ctrl+1. Now any time you press 1, those vertices are selected again.

A lasso select would be great, as rectangular select can be unwieldy at times. Maybe we could do this by holding shift or alt, we'll have to give it some thought.

2) We have reproduced losing triangles when moving vertices close. We'll get this fixed ASAP.

3) I think it's a good idea to have something happen when dropping an image on an existing attachment. It sounds like you are wanting the attachment to be duplicated, then renamed to match the image. It would also make sense for a new linked mesh to be created, then renamed to match the image. Which of these you want depends on what you are doing at the time. I think it may be best not to duplicate or create a linked mesh, but to just rename the attachment when an image is dropped on it. The workflow would be:

i) Duplicate mesh (or create linked mesh).
ii) Drop image on new mesh (instead of typing the image path).

We can have this done quickly.
