### ISSUE TITLE
Enabling `Power of two` and `Square` may be the cause the packed texture has a large whitespace

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#726]
In the Texture Packer setting, if you enabled `Power of two` and `Square`, the packed texture may have a large whitespace. It is known that `Polygons` packing can create inefficient whitespace since it requires so many calculations, but this issue also happens if `Rectangles` packing is selected. For example, the attached Spine project's textures can be packed at `512 * 512px`, but if the `Max width/height` are set to more than `2048 * 2048px`, they will be packed at `1024 * 1024px`. If the `Max width/height` are set to `1024 * 1024px` or `512 * 512px`, they will be packed at `512 * 512px`:
[Enabling `Power of two` and `Square` may be the cause the packed texture has a large whitespace.zip](https://github.com/EsotericSoftware/spine-editor/files/10379387/Enabling.Power.of.two.and.Square.may.be.the.cause.the.packed.texture.has.a.large.whitespace.zip)

![Enabling-`Power-of-two`-and-`Square`-may-be-the-cause-the-packed-texture-has-a-large-whitespace](https://user-images.githubusercontent.com/85478846/211475615-ab98d89e-bc40-484c-868c-366540a6314a.png)

As described above, changing `Max width/height` would work around this issue, but we should improve so that Spine can output the texture with optimal size.

**The version of this issue tested:**
Spine v4.1.17

**Related forum post:**
http://esotericsoftware.com/forum/x-18471

**Comment by NathanSweet** [comment]
The input images pack into a smaller area when the page is 1024x1024. They can fit in 512x512 but the area on the page that the images use up is more. This makes the packer prefer the larger page size.

The packer doesn't know if more images will be added to a page later. That can happen when different folders are packed into the same page. Or, when an atlas has multiple pages, it tries to pack images into free space on existing pages before adding a new page. For those reasons it uses the space taken up by packed images as the heuristic, not the size of the page image.

I think it makes sense to target a minimal page image size when power of two or square is chosen, even if the packing isn't as tight, because those options can easily result in a large amount of wasted space. We've made the change in 4.1.18.
