### ISSUE TITLE
Unable to run export CLI Command on Linux Server

### ISSUE THREAD

**Issue by XRFate** [EsotericSoftware/spine-editor#750]
`
Starting: Spine 4.1.23 Essential
Spine 4.1.23 Essential
Licensed to: *****
ERROR: Unable to create the OpenGL display.
[error] Error initializing the OpenGL display.
   at s.jTp.T(_:103)
   <events>
Cause: [NoClassDefFoundError] Could not initialize class s.tOG
   at s.jTp.T(_:101) ...
ERROR: Please note libxrandr that is required, for example:
ERROR: sudo apt-get install x11-xserver-utils
`

while exporting png on a linux server, libxrandr can not run successfully.

**Comment by badlogic** [comment]
Did you install libxrandr as per the error message? What exact Linux distribution and version are you running this on?

**Comment by XRFate** [comment]
In deed, libxrandr2 was installed thru X11-server installation. `xrandr` can be called, but no monitor/display was found. This server was deployed on AWS . Here is the config `ubuntu-jammy-22.04-amd64-server`. Is it true that the picture export API must have a screen display in use or it will hit this error?

**Comment by NathanSweet** [comment]
Posting your entire `spine.log` file would help us see the full error, though I don't know that would lead to a solution. You can still redact your license info.

Image and video export uses OpenGL for rendering. I'm not sure if it's possible to initialize OpenGL on Linux without a real display. While I'm very familiar with Linux servers, I'm not an expert at running a Linux desktop, but it may help to install `xserver` and `xinit`. Otherwise you may be able to use a lightweight desktop environment, like `xfce` or `fluxbox`.

Another option could be to write software to generate images from your Spine data. You can use the Spine Runtimes to load the data, then you'd need to choose a graphics toolkit compatible with a headless server. Some example code can be found in [PngExportTest.java](https://github.com/EsotericSoftware/spine-runtimes/blob/4.1/spine-libgdx/spine-libgdx-tests/src/com/esotericsoftware/spine/PngExportTest.java). It uses libgdx/Java/OpenGL which may not be appropriate for a headless server, but it still shows the general approach applicable to other languages.

**Comment by XRFate** [comment]
Here is a full report:

> Spine Launcher 4.1.12
Esoteric Software LLC (C) 2013-2022 | http://esotericsoftware.com/
Linux amd64 5.19.0-1028-aws
WARNING: Unable to validate graphics environment.
[awt.Headless]
No X11 DISPLAY variable was set,
but this program performed an operation which requires it.
   at sun.java2d.HeadlessGraphicsEnvironment.getDefaultScreenDevice(Unknown Source)
   at s.GgK._(_:495)
   at com.esotericsoftware.spine.launcher.Launcher._(_:146)
   at com.esotericsoftware.spine.launcher.Launcher.L(_:102)
   at com.esotericsoftware.spine.launcher.Launcher.<init>(_:51)
   at s.LGD._(_:197)
Starting: Spine 4.1.23 Essential
Spine 4.1.23 Essential
Licensed to: Patrick <[patrick@kotoko.ai](mailto:patrick@kotoko.ai)>
ERROR: Unable to create the OpenGL display.
[error] Error initializing the OpenGL display.
   at s.jTp.T(_:103)
Cause: [NoClassDefFoundError] Could not initialize class s.tOG
   at s.jTp.T(_:101) ...
ERROR: Please note libxrandr that is required, for example:
ERROR: sudo apt-get install x11-xserver-utils

We tested `xserver-xorg` and `xinit`, it outputs the same error. Thanks for these info. I probaby will try to deploy a desktop enviroment. I will close this Issue in the mean time. 

PS. Did you mean you are familiar with Linux desktop not the server(headless)? I kind of confused.

**Comment by NathanSweet** [comment]
Sorry this fell off our radar. It wants a `DISPLAY` environment variable. Maybe `export DISPLAY=:0.0`?

Ultimately image and video export require OpenGL, so likely need a desktop of some sort.
