### ISSUE TITLE
folder spine to dot spine (.spine)

### ISSUE THREAD

**Issue by djmisterjon** [EsotericSoftware/spine-editor#769]
Sorry, i know I have a bit of a quirk, but this has been bothering me for a while.
Do you think you could add a dot as a suffix to the '.spine' folder  in the OS profile, like other software that adds their profile data there?
It makes things cleaner because this is where he OS Windows also manages links to personal folders, and it can quickly become an organizational mess without good practices

of you can change your profile folder from `spine` to `.spine` 😁 geek maniak organisation will thank you.
![image](https://github.com/EsotericSoftware/spine-editor/assets/24865815/d411be97-a20c-4f7e-b01e-83b2748aa296)

thanks

**Comment by NathanSweet** [comment]
It is not a convention to use a `.` prefix on Windows. It is on Linux and some apps do it on Windows.

The Windows way is to place files in `AppData` under `Roaming` or `Local` or `LocalLow`. While that is the standard way of doing it, it's pretty ugly since most users have no idea what those mean. It also means there are 3 locals users have to look to find files.

I understand it mixes with other folders and that's not great, but unfortunately it's too late to change for Spine now. It would be complicated to shuffle the folders around and we wouldn't want to have 2 places to look. Spine isn't the only app that places files in the user folder. Also Windows itself files the user folder with junk like `3D Objects` that can be difficult to get rid of. It's just not a place that can be kept tidy.

**Comment by FabianoIlCapo** [comment]
So damn true, Nate
