### ISSUE TITLE
Allow specification of frame rate for rendering

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-editor#79]
One feature that I was looking for in the test and I read that was actually absent is the ability to create animation at 24fps easily.  I read a workaround is to just playback at 80% and render accordingly, but is it planned to make it easier to change frame rate in the near future? If not, should include this work around in the faqs, as it might open up the program to filmmakers more since the program is more optimized/aimed towards game animation and this workaround is not immediately obvious since you guys do things a little differently (definitely for the better for most things lol)

One other feature that I would suggest is a ruler that you can of course toggle.  Off by default, wouldn't be needed too often, but would be nice to have.

**Comment by pharan** [comment]
This is a "Custom Dopesheet Framerate".
It's more a matter of artist workflow than output/render, since times are always stored as float seconds anyway.

It's a recurring request in the forums, especially coming from classical/hand-drawn animators who are very attuned to base 12 and 24 timings (eg, they know that a certain pace of run is a certain number of frames, or a certain snappy movement is a certain number of frames).

Another case that it handles that I want is 60fps on the dopesheet.
This is useful for: 
- incorporating high-framerate image sequences into skeletons (handled later with region sequences)
- Rely on snapping when finely-tuning fast animations (like a very fast sword swing). Fast motions can visibly break (if you don't key it) or feel too rigid (if you use a stepped curve even at 30fps) if you don't specify the poses at 60fps. The problem is exacerbated if the game involves periods slow motion, especially at the moment of impact (this is a common technique in fighting games).

**Comment by NathanSweet** [comment]
In 3.5.00-beta:

![](http://n4te.com/x/621-YRb1.png)

Unlike the speed slider, FPS is exported and used in the runtimes. It's one setting for the whole project and changing it doesn't affect existing keys (animations just run faster or slower). Spine allows multiple skeletons and playback shares the timeline, so specifying FPS per animation doesn't make sense (we don't want to manage two timeline positions).
