### ISSUE TITLE
[3.4.01] Export from editor produces different #vertices than export from CLI

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-editor#81]
See http://esotericsoftware.com/forum/Command-line-bug-6750?p=31297#p31297

**Comment by NathanSweet** [comment]
I'm not seeing a skeleton size of 0,0. That should have been fixed in [3.4.00](http://esotericsoftware.com/spine-changelog#v3-4-00). Spine tries to load the images to determine their size, else it uses the size from when the project file was saved. Spine will report a warning, "images path not found", if it can't find the images folder when exporting.

I see bones showing up in the data in a different order. This causes weighted mesh vertices to change, as they contain bone indices. Fixed in 3.4.02.
