### ISSUE TITLE
Background checkbox and Deform timelines (json/binary fails to load)

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#87]
case:
In the editor, have a deform timeline that deforms a mesh that's been marked "background".
- the mesh is not included when exporting to binary/json
- the deform timeline is exported in the animation
- when the runtime tries to load the SkeletonData, it fails when it tries to find the target VertexAttachment of the DeformTimeline because it doesn't exist (it wasn't exported as part of the SkeletonData).
- no warnings are shown in the editor interface. No error messages are logged/shown when exporting.
- the Background checkbox tooltip reads:<br>
  ![](http://i.imgur.com/R73eBpn.png)
- When the runtime loading fails, it doesn't log the missing target VertexAttachment name, or the DeformTimeline's animation name.

expected:
- clear indicators in the UI to warn the user that they have images marked "background".
- clear messages in the editor, and at runtime, of the related errors, if it may have errors.
- Question: discard the DeformTimeline when loading if it can't find its target (with a warning)? Include the target when exporting despite it being marked as "background" like the tooltip says?

A couple of users already had this problem.

**Comment by NathanSweet** [comment]
Fixed in 3.5.16-beta, background mesh is now exported if keyed in an a attachment timeline or deform timeline, and a warning is shown.

At runtime, valid data is expected and the loader does not try to handle invalid data and provide exact error messages. spine-libgdx does more than most runtimes, since it's used in the editor and Skeleton Viewer.
